# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4057e9539c3a033bc3b1a23af027cb6eec5d5b6dd3e3e08c788e5ae937cbe74f3ffbff50e4aa186824236d2d02cf518e572febdee83807e3883e822647ccfffa

test:
  secret_key_base: c496a96da48f92697f8e26aa643f855c0374b8c238b92b1d1363f7f3c9befc375cec1575a5978a2746f841ba8179400932b559fb0839ef0491e0e25aeb0b0ae8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
